//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: configuration.proto

package bdlsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ConfigMetadata is the channel-level configuration of the BDLS consenter.
// It is stored in ConsensusType.Metadata on a config block and parsed by
// HandleChain when constructing a Chain for the channel. Shape is kept
// deliberately close to etcdraft.ConfigMetadata so existing operator
// tooling (configtxgen templates, admin-api pacers) can lift the patterns
// they already use.
type ConfigMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Consenters in this channel's BDLS consensus group. Order is NOT
	// significant — the run-time BDLS participant id is derived from the
	// PEM-decoded server cert public key, not from position in this list.
	Consenters []*Consenter `protobuf:"bytes,1,rep,name=consenters,proto3" json:"consenters,omitempty"`
	// Tunables for the consensus state machine. Zero means "use library
	// default" for every field.
	Options       *Options `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigMetadata) Reset() {
	*x = ConfigMetadata{}
	mi := &file_configuration_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigMetadata) ProtoMessage() {}

func (x *ConfigMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigMetadata.ProtoReflect.Descriptor instead.
func (*ConfigMetadata) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{0}
}

func (x *ConfigMetadata) GetConsenters() []*Consenter {
	if x != nil {
		return x.Consenters
	}
	return nil
}

func (x *ConfigMetadata) GetOptions() *Options {
	if x != nil {
		return x.Options
	}
	return nil
}

// Consenter carries the network identity of a single BDLS participant.
// Mirrors orderer.smartbft.Consenter so cluster-side TLS bootstrapping
// and Fabric's channelconfig.Consenters() stay consistent.
type Consenter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// GRPC host used by the cluster transport.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// GRPC port used by the cluster transport.
	Port uint32 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	// Server (TLS) certificate in PEM. The secp256k1 / P-256 public key
	// extracted from this cert is what BDLS uses to identify the peer.
	ServerTlsCert []byte `protobuf:"bytes,3,opt,name=server_tls_cert,json=serverTlsCert,proto3" json:"server_tls_cert,omitempty"`
	// Client (TLS) certificate in PEM, used when this orderer dials others.
	ClientTlsCert []byte `protobuf:"bytes,4,opt,name=client_tls_cert,json=clientTlsCert,proto3" json:"client_tls_cert,omitempty"`
	// MSP identity bytes — carried here for parity with smartbft's
	// Consenter; not used by the BDLS state machine itself.
	Identity      []byte `protobuf:"bytes,5,opt,name=identity,proto3" json:"identity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Consenter) Reset() {
	*x = Consenter{}
	mi := &file_configuration_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Consenter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Consenter) ProtoMessage() {}

func (x *Consenter) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Consenter.ProtoReflect.Descriptor instead.
func (*Consenter) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{1}
}

func (x *Consenter) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *Consenter) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Consenter) GetServerTlsCert() []byte {
	if x != nil {
		return x.ServerTlsCert
	}
	return nil
}

func (x *Consenter) GetClientTlsCert() []byte {
	if x != nil {
		return x.ClientTlsCert
	}
	return nil
}

func (x *Consenter) GetIdentity() []byte {
	if x != nil {
		return x.Identity
	}
	return nil
}

// Options carries the paper's Δ timeouts (Section 8.2) plus batch-cutter
// parameters. All durations are milliseconds; zero means "library default".
type Options struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Δ₀ — round-change stage timeout.
	Delta0Ms int64 `protobuf:"varint,1,opt,name=delta0_ms,json=delta0Ms,proto3" json:"delta0_ms,omitempty"`
	// Δ₁ — lock stage timeout for non-leader.
	Delta1Ms int64 `protobuf:"varint,2,opt,name=delta1_ms,json=delta1Ms,proto3" json:"delta1_ms,omitempty"`
	// Δ'₁ — lock stage timeout for leader.
	DeltaPrime1Ms int64 `protobuf:"varint,3,opt,name=delta_prime1_ms,json=deltaPrime1Ms,proto3" json:"delta_prime1_ms,omitempty"`
	// Δ₂ — commit stage timeout.
	Delta2Ms int64 `protobuf:"varint,4,opt,name=delta2_ms,json=delta2Ms,proto3" json:"delta2_ms,omitempty"`
	// Δ₃ — lock-release stage timeout.
	Delta3Ms int64 `protobuf:"varint,5,opt,name=delta3_ms,json=delta3Ms,proto3" json:"delta3_ms,omitempty"`
	// Base network latency used by BDLS.SetLatency. The Δ* knobs above
	// override the per-stage derivation from this value; it is still used
	// as a lower bound for run-loop scheduling.
	LatencyMs int64 `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// Batching knobs, following the etcdraft / smartbft convention.
	RequestBatchMaxCount      uint64 `protobuf:"varint,7,opt,name=request_batch_max_count,json=requestBatchMaxCount,proto3" json:"request_batch_max_count,omitempty"`
	RequestBatchMaxBytesSize  uint64 `protobuf:"varint,8,opt,name=request_batch_max_bytes_size,json=requestBatchMaxBytesSize,proto3" json:"request_batch_max_bytes_size,omitempty"`
	RequestBatchMaxIntervalMs int64  `protobuf:"varint,9,opt,name=request_batch_max_interval_ms,json=requestBatchMaxIntervalMs,proto3" json:"request_batch_max_interval_ms,omitempty"`
	// When true the BDLS library will only advance past a decided height
	// after 2t+1 distinct participants have re-broadcast the <decide>,
	// closing the Section-9 fork window. Defaults to true for new channels
	// — the legacy single-flood path exists only for backwards compat.
	ReliableDecide bool `protobuf:"varint,10,opt,name=reliable_decide,json=reliableDecide,proto3" json:"reliable_decide,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Options) Reset() {
	*x = Options{}
	mi := &file_configuration_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Options) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Options) ProtoMessage() {}

func (x *Options) ProtoReflect() protoreflect.Message {
	mi := &file_configuration_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Options.ProtoReflect.Descriptor instead.
func (*Options) Descriptor() ([]byte, []int) {
	return file_configuration_proto_rawDescGZIP(), []int{2}
}

func (x *Options) GetDelta0Ms() int64 {
	if x != nil {
		return x.Delta0Ms
	}
	return 0
}

func (x *Options) GetDelta1Ms() int64 {
	if x != nil {
		return x.Delta1Ms
	}
	return 0
}

func (x *Options) GetDeltaPrime1Ms() int64 {
	if x != nil {
		return x.DeltaPrime1Ms
	}
	return 0
}

func (x *Options) GetDelta2Ms() int64 {
	if x != nil {
		return x.Delta2Ms
	}
	return 0
}

func (x *Options) GetDelta3Ms() int64 {
	if x != nil {
		return x.Delta3Ms
	}
	return 0
}

func (x *Options) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *Options) GetRequestBatchMaxCount() uint64 {
	if x != nil {
		return x.RequestBatchMaxCount
	}
	return 0
}

func (x *Options) GetRequestBatchMaxBytesSize() uint64 {
	if x != nil {
		return x.RequestBatchMaxBytesSize
	}
	return 0
}

func (x *Options) GetRequestBatchMaxIntervalMs() int64 {
	if x != nil {
		return x.RequestBatchMaxIntervalMs
	}
	return 0
}

func (x *Options) GetReliableDecide() bool {
	if x != nil {
		return x.ReliableDecide
	}
	return false
}

var File_configuration_proto protoreflect.FileDescriptor

const file_configuration_proto_rawDesc = "" +
	"\n" +
	"\x13configuration.proto\x12\forderer.bdls\"z\n" +
	"\x0eConfigMetadata\x127\n" +
	"\n" +
	"consenters\x18\x01 \x03(\v2\x17.orderer.bdls.ConsenterR\n" +
	"consenters\x12/\n" +
	"\aoptions\x18\x02 \x01(\v2\x15.orderer.bdls.OptionsR\aoptions\"\x9f\x01\n" +
	"\tConsenter\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12&\n" +
	"\x0fserver_tls_cert\x18\x03 \x01(\fR\rserverTlsCert\x12&\n" +
	"\x0fclient_tls_cert\x18\x04 \x01(\fR\rclientTlsCert\x12\x1a\n" +
	"\bidentity\x18\x05 \x01(\fR\bidentity\"\xa6\x03\n" +
	"\aOptions\x12\x1b\n" +
	"\tdelta0_ms\x18\x01 \x01(\x03R\bdelta0Ms\x12\x1b\n" +
	"\tdelta1_ms\x18\x02 \x01(\x03R\bdelta1Ms\x12&\n" +
	"\x0fdelta_prime1_ms\x18\x03 \x01(\x03R\rdeltaPrime1Ms\x12\x1b\n" +
	"\tdelta2_ms\x18\x04 \x01(\x03R\bdelta2Ms\x12\x1b\n" +
	"\tdelta3_ms\x18\x05 \x01(\x03R\bdelta3Ms\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x125\n" +
	"\x17request_batch_max_count\x18\a \x01(\x04R\x14requestBatchMaxCount\x12>\n" +
	"\x1crequest_batch_max_bytes_size\x18\b \x01(\x04R\x18requestBatchMaxBytesSize\x12@\n" +
	"\x1drequest_batch_max_interval_ms\x18\t \x01(\x03R\x19requestBatchMaxIntervalMs\x12'\n" +
	"\x0freliable_decide\x18\n" +
	" \x01(\bR\x0ereliableDecideBGZEgithub.com/hyperledger/fabric/orderer/consensus/bdls/protos;bdlsprotob\x06proto3"

var (
	file_configuration_proto_rawDescOnce sync.Once
	file_configuration_proto_rawDescData []byte
)

func file_configuration_proto_rawDescGZIP() []byte {
	file_configuration_proto_rawDescOnce.Do(func() {
		file_configuration_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)))
	})
	return file_configuration_proto_rawDescData
}

var file_configuration_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_configuration_proto_goTypes = []any{
	(*ConfigMetadata)(nil), // 0: orderer.bdls.ConfigMetadata
	(*Consenter)(nil),      // 1: orderer.bdls.Consenter
	(*Options)(nil),        // 2: orderer.bdls.Options
}
var file_configuration_proto_depIdxs = []int32{
	1, // 0: orderer.bdls.ConfigMetadata.consenters:type_name -> orderer.bdls.Consenter
	2, // 1: orderer.bdls.ConfigMetadata.options:type_name -> orderer.bdls.Options
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_configuration_proto_init() }
func file_configuration_proto_init() {
	if File_configuration_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configuration_proto_rawDesc), len(file_configuration_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configuration_proto_goTypes,
		DependencyIndexes: file_configuration_proto_depIdxs,
		MessageInfos:      file_configuration_proto_msgTypes,
	}.Build()
	File_configuration_proto = out.File
	file_configuration_proto_goTypes = nil
	file_configuration_proto_depIdxs = nil
}
