//
//Copyright IBM Corp. All Rights Reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: metadata.proto

package bdlsproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BlockMetadata is the per-block BDLS metadata written into the
// BlockMetadata.Metadata[BlockMetadataIndex_ORDERER] slot. It is the
// source of truth for finality — both the BDLS state machine and any
// external verifier (via bdls.ValidateDecideMessage) read from it.
type BlockMetadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BDLS height at which the block was finalised. This is strictly
	// monotone per channel and tracks the block number, not the
	// round-within-height counter.
	BdlsHeight uint64 `protobuf:"varint,1,opt,name=bdls_height,json=bdlsHeight,proto3" json:"bdls_height,omitempty"`
	// Round within the height at which the block was finalised. Useful
	// for debugging leader-selection / view-change behaviour; not used
	// for external verification.
	BdlsRound uint64 `protobuf:"varint,2,opt,name=bdls_round,json=bdlsRound,proto3" json:"bdls_round,omitempty"`
	// Serialised BDLS <decide> message (the bytes returned by
	// Consensus.CurrentProof). External verifiers feed this directly
	// into bdls.ValidateDecideMessage together with the target state
	// to confirm finality without touching the rest of the ledger.
	BdlsDecideProof []byte `protobuf:"bytes,3,opt,name=bdls_decide_proof,json=bdlsDecideProof,proto3" json:"bdls_decide_proof,omitempty"`
	// Leader participant id at the moment of finalisation. Mirrors
	// orderer.etcdraft.BlockMetadata's RaftIndex in spirit.
	LeaderId      uint64 `protobuf:"varint,4,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMetadata) Reset() {
	*x = BlockMetadata{}
	mi := &file_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMetadata) ProtoMessage() {}

func (x *BlockMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMetadata.ProtoReflect.Descriptor instead.
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return file_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *BlockMetadata) GetBdlsHeight() uint64 {
	if x != nil {
		return x.BdlsHeight
	}
	return 0
}

func (x *BlockMetadata) GetBdlsRound() uint64 {
	if x != nil {
		return x.BdlsRound
	}
	return 0
}

func (x *BlockMetadata) GetBdlsDecideProof() []byte {
	if x != nil {
		return x.BdlsDecideProof
	}
	return nil
}

func (x *BlockMetadata) GetLeaderId() uint64 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

var File_metadata_proto protoreflect.FileDescriptor

const file_metadata_proto_rawDesc = "" +
	"\n" +
	"\x0emetadata.proto\x12\forderer.bdls\"\x98\x01\n" +
	"\rBlockMetadata\x12\x1f\n" +
	"\vbdls_height\x18\x01 \x01(\x04R\n" +
	"bdlsHeight\x12\x1d\n" +
	"\n" +
	"bdls_round\x18\x02 \x01(\x04R\tbdlsRound\x12*\n" +
	"\x11bdls_decide_proof\x18\x03 \x01(\fR\x0fbdlsDecideProof\x12\x1b\n" +
	"\tleader_id\x18\x04 \x01(\x04R\bleaderIdBGZEgithub.com/hyperledger/fabric/orderer/consensus/bdls/protos;bdlsprotob\x06proto3"

var (
	file_metadata_proto_rawDescOnce sync.Once
	file_metadata_proto_rawDescData []byte
)

func file_metadata_proto_rawDescGZIP() []byte {
	file_metadata_proto_rawDescOnce.Do(func() {
		file_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)))
	})
	return file_metadata_proto_rawDescData
}

var file_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metadata_proto_goTypes = []any{
	(*BlockMetadata)(nil), // 0: orderer.bdls.BlockMetadata
}
var file_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_metadata_proto_init() }
func file_metadata_proto_init() {
	if File_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metadata_proto_rawDesc), len(file_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metadata_proto_goTypes,
		DependencyIndexes: file_metadata_proto_depIdxs,
		MessageInfos:      file_metadata_proto_msgTypes,
	}.Build()
	File_metadata_proto = out.File
	file_metadata_proto_goTypes = nil
	file_metadata_proto_depIdxs = nil
}
